-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 22:08:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `client_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NULL,
  `email` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `Clientscol_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commandes` (
  `commande_id` INT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `date_commande` DATE NOT NULL,
  `montant_total` DECIMAL(10,2) NULL,
  `status` ENUM('en cours', 'livrée', 'annulée') NULL,
  `Clients_client_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`commande_id`),
  INDEX `fk_Commandes_Clients_idx` (`Clients_client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Commandes_Clients`
    FOREIGN KEY (`Clients_client_id`)
    REFERENCES `mydb`.`Clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
